SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
INNER JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' and FIRST_HALF .TOTAL_ORDER >= 3000
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;

// 테이블에 공통인 FLAVOR 로 INNER JOIN 해서 컬럼 앞 테이블 명시해주고, 해서 그나마 쉬웠음.. 서브쿼리로도 될 거 같은데..

  <2번째 방법> => 이것 보다 이너 조인이 나을 듯..?
SELECT FLAVOR
FROM ICECREAM_INFO
WHERE INGREDIENT_TYPE = 'fruit_based'
AND FLAVOR IN (
    SELECT FLAVOR
    FROM FIRST_HALF
    WHERE TOTAL_ORDER >= 3000
)
ORDER BY (
    SELECT TOTAL_ORDER
    FROM FIRST_HALF
    WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
) DESC;
