SELECT HISTORY_ID, 
        CAR_ID, 
        DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, 
        DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    IF(DATEDIFF(END_DATE, START_DATE) + 1 >= 30, '장기 대여', '단기 대여') AS RENT_TYPE
    
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where DATE_FORMAT(START_DATE, '%Y-%m') = '2022-09'
order by HISTORY_ID desc;

// DATE_FORMAT => SELECT DATE_FORMAT('20000119', '%Y.%m.%d')→ 2000.01.19
// DATEDIFF => SELECT DATEDIFF(DAY,   '2021-06-12', '2021-07-13') 두 기간 비교
